on: [pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Clojure
        run: |
          curl -O https://download.clojure.org/install/linux-install-1.10.1.469.sh
          chmod +x linux-install-1.10.1.469.sh
          sudo ./linux-install-1.10.1.469.sh
      - name: Lint
        run: |
          clojure -A:lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Clojure
        run: |
          curl -O https://download.clojure.org/install/linux-install-1.10.1.469.sh
          chmod +x linux-install-1.10.1.469.sh
          sudo ./linux-install-1.10.1.469.sh
      - name: Build lambdas
        run: |
          cd example
          clojure -m stedi.lambda.build
      - name: Run tests
        run: |
          clojure -A:dev:test
